site-title: "Specifiable"
description: "On modeling, formal methods and correct-by-construction software."
posts:
  - title: "REST's semantics are informal. Here is a formal alternative."
    url: "posts/entity-protocol.html"
    date: "2026-03-25"
    description: "Starting from REST, we develop a formal model for distributed state from mathematical definition to working implementation."
mainfont: "'Roboto', sans-serif"
fontsize: "1rem"
fontweight: "300"
linestretch: "1.5"
monocolor: "#2698ba"
monobackgroundcolor: "#c8c9ca"
maxwidth: "1050px"
