site-url: "https://jskri.github.io"
site-title: "Specifiable"
description: "On modeling, formal methods and correct-by-construction software."
about-description: "About the author of Specifiable."
author: "https://github.com/jskri"
posts:
  - title: "REST's semantics are informal. Here is a formal alternative."
    url: "/posts/entity-protocol.html"
    date: "2026-03-25"
    description: "Starting from REST, we develop a formal model for distributed state from mathematical definition to working implementation."
fonts:
  - family: "Roboto"
    style: "normal"
    weight: "300"
    path: "/assets/fonts/roboto-v51-latin-300.woff2"
    format: "woff2"
  - family: "Roboto"
    style: "normal"
    weight: "500"
    path: "/assets/fonts/roboto-v51-latin-500.woff2"
    format: "woff2"
mainfont: "'Roboto', sans-serif"
fontsize: "1rem"
fontweight: "300"
linestretch: "1.6"
maxwidth: "1050px"
favicon-path: "/assets/img/favicon.svg"
