name: Build and publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/jskri/blog-builder@sha256:e1a73bb063fd57a4caef529e530e172d55fa002cff1f4e99ffde3774b4c177af # v1.0.4

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Build site
        run: make all

      - name: Publish site
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
