name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ghcr.io/jskri/blog-builder@sha256:43afe4c7797c1fd784acf44686440c4786c362e098f010713d28da6dfc335ea6 # v1.0.0

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build site
        run: make all

      - name: Publish site
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
